### ISSUE TITLE
Protobufs/JSPB causes build errors with Closure Library

### ISSUE THREAD

**Issue by sgammon** [google/closure-builder#7]
Hey there,

When I try to build my regular Closure-based project, all looks good and works well. I take a step further and embed my JavaScript protobuf files, built in `closure` mode.

It starts to complain about `jspb.Message`, etc, so I git-submodule in `protobuf` and include those via `protobuf/js/message.js`, `protobuf/js/map.js`, and so on.

Those dependencies pull in `goog.asserts`, and from there, the build explodes with errors related to Closure library:

```
/node_modules/closure-builder/third_party/closure-library/closure/goog/editor/plugins/abstractbubbleplugin.js:37: ERROR - required "goog.ui.Component" namespace never provided
goog.require('goog.ui.Component');
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

node_modules/closure-builder/third_party/closure-library/closure/goog/testing/multitestrunner.js:39: ERROR - required "goog.ui.ServerChart" namespace never provided
goog.require('goog.ui.ServerChart');
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

node_modules/closure-builder/third_party/closure-library/closure/goog/testing/multitestrunner.js:40: ERROR - required "goog.ui.TableSorter" namespace never provided
goog.require('goog.ui.TableSorter');
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

node_modules/closure-builder/third_party/closure-library/closure/goog/testing/ui/rendererasserts.js:25: ERROR - required "goog.ui.ControlRenderer" namespace never provided
goog.require('goog.ui.ControlRenderer');
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

node_modules/closure-builder/third_party/closure-library/closure/goog/tweak/tweakui.js:42: ERROR - required "goog.ui.Zippy" namespace never provided
goog.require('goog.ui.Zippy');
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

More aggravating, still, is that including any of these components yields more errors. I tried to specify `node_modules/closure-builder/third_party/closure-library/closure/goog/base.js` and `[...]/closure/goog/ui/component.js`, but that only yields more and different errors:

```
node_modules/closure-builder/third_party/closure-library/closure/goog/ui/component.js:24: ERROR - namespace "goog.ui.Component" cannot be provided twice
goog.provide('goog.ui.Component');
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

node_modules/closure-builder/third_party/closure-library/closure/goog/ui/component.js:25: ERROR - namespace "goog.ui.Component.Error" cannot be provided twice
goog.provide('goog.ui.Component.Error');
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Can someone help? I have personally and professionally signed the Google CLA and am happy to assist in any way.

**Comment by MarkusBordihn** [comment]
Thanks for your report protobuf (https://github.com/google/protobuf) is currently not implemented, because its requires an protobuf compiler.

But we will try to add this in the next version.

**Comment by sgammon** [comment]
I understand, and that's okay - I'm building my protobufs elsewhere. I have them in `commonjs`, `browser`, `es6` and `closure` forms already.

The problem is, when I try to _use_ them from `closure-builder`, I encounter the above issues.

Thank you for writing back. Is there anything I can do to fix this? Perhaps compile my protos differently?

**Comment by sgammon** [comment]
@MarkusBordihn: it seems most of my builds get this after enabling `debug` and `trace`:

For building my protos only:
```
Set loglevel to trace
Get Build configuration for goog.protos
Type: javascript
Closure namespace: 
Require ECMAScript6: false
Require closure export: false
Require closure library: false
Require soy i18n: false
Require soy library: false
License file: src/app/license.txt
[...]
```

For building the protos with my app:
```
Set loglevel to trace
Get Build configuration for bloombox.dashboard
Type: CLOSURE
Closure namespace: 
Require ECMAScript6: true
Require closure export: true
Require closure library: false
Require soy i18n: false
Require soy library: false
License file: src/app/license.txt
```

It is still not deciding to include the closure library.

**Comment by sgammon** [comment]
By the way, I am using protojs compiled such that it outputs in the following manner, just so you have an idea how I am using Closure here with protojs:

```js
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.exportSymbol('proto.base.ProductKey', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.base.ProductKey = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.base.ProductKey, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.base.ProductKey.displayName = 'proto.base.ProductKey';
}

[...]
```

**Comment by sgammon** [comment]
i have fixed this for now by simply tricking `closure-builder` into including `goog.ui`, by including some token in it (in a `goog.require`) that mentions `goog.ui`

i think in my case i am importing some static property or CSS class or something. simply doing that fixes the issue via side effects
